# Generated by Django 6.0 on 2025-12-22 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_APP', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockData',
            new_name='Stock',
        ),
    ]
