# Generated by Django 6.0 on 2025-12-22 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_APP', '0002_rename_stockdata_stock'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stock',
            new_name='Stock_Data',
        ),
    ]
