# Generated by Django 6.0 on 2025-12-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_APP', '0003_rename_stock_stock_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_Stock_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('nepal_dt', models.DateField()),
                ('utc_dt', models.DateField()),
                ('open_price', models.FloatField()),
                ('high_price', models.FloatField()),
                ('low_price', models.FloatField()),
                ('close_price', models.FloatField()),
                ('volume', models.BigIntegerField()),
                ('change', models.FloatField()),
                ('change_percent', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Stock_Data',
        ),
    ]
