# Generated by Django 6.0 on 2026-01-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_APP', '0004_new_stock_data_delete_stock_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_stock_data',
            name='change_percent',
            field=models.FloatField(),
        ),
    ]
