# Generated by Django 6.0 on 2026-01-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_APP', '0006_transaction_wallet_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='change',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watchlist',
            name='close_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watchlist',
            name='nepal_dt',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
    ]
